server.port=8080

#SpringData JPA
spring.datasource.url=jdbc://postgresql://dpg-d7ueuehpo60c73b2gdng-a.oregon-postgres.render.com:5432/platzi_play_db_4fzc
spring.datasource.username=john
spring.datasource.password=dn6bHTT8m6kkWXYsleUyMXp4dc2VUB9P
#LangChain4j config
langchain4j.open-ai.chat-model.api-key=demo