spring.profiles.active=dev
spring.application.name="Platzi Play"

#Server config
server.servlet.context-path=/platzi-play/api

#langchain4j
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

#PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
